name: Trigger an Azure Machine Learning job with push

on:
  push:
      branches:
          - main

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Train a classification model in development environment
      run: az ml job create --file ./src/dev-job.yml --workspace-name ckurt-ml-workspace --resource-group CK_AI-ML --stream
  production:
    runs-on: ubuntu-latest
    needs: experiment
    environment: production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Train a classification model in production environment
      run: az ml job create --file ./src/prod-job.yml --workspace-name ckurt-ml-workspace --resource-group CK_AI-ML --stream
  
